source 'https://rubygems.org'
gem 'rails', '~> 2.3.18'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'bcrypt', '~> 3.1.12'

# bundler requires these gems in all environments
# gem 'nokogiri', '1.4.2'
# gem 'geokit'

group :development do
  # bundler requires these gems in development
  # gem 'rails-footnotes'
end

group :test do
  # bundler requires these gems while running tests
  # gem 'rspec'
  # gem 'faker'
end
